Repository devblogs-ir/Over-dotnet-CLI, pull requests merged in 2023-12, with the labels that each got.

#7 Feat/morvarid arab
  sources/Morvarid Arab/README.md
  sources/Morvarid Arab/maha-builder/maha-builder/Program.cs
  sources/Morvarid Arab/maha-builder/maha-builder/maha-builder.csproj
  sources/Morvarid Arab/src/SrcClassLib/Class1.cs
  sources/Morvarid Arab/src/SrcClassLib/SrcClassLib.csproj
  sources/Morvarid Arab/src/SrcConsoleApp/Program.cs
  sources/Morvarid Arab/src/SrcConsoleApp/SrcConsoleApp.csproj
  sources/Morvarid Arab/src/SrcWebApi/Program.cs
  sources/Morvarid Arab/src/SrcWebApi/Properties/launchSettings.json
  sources/Morvarid Arab/src/SrcWebApi/SrcWebApi.csproj
  sources/Morvarid Arab/src/SrcWebApi/SrcWebApi.http
  sources/Morvarid Arab/src/SrcWebApi/appsettings.Development.json
  sources/Morvarid Arab/src/SrcWebApi/appsettings.json
  sources/Morvarid Arab/test/SrcClassLib_Test/GlobalUsings.cs
  sources/Morvarid Arab/test/SrcClassLib_Test/SrcClassLib_Test.csproj
  sources/Morvarid Arab/test/SrcClassLib_Test/UnitTest1.cs
  sources/Morvarid Arab/test/SrcConsoleApp_Test/GlobalUsings.cs
  sources/Morvarid Arab/test/SrcConsoleApp_Test/SrcConsoleApp_Test.csproj
  sources/Morvarid Arab/test/SrcConsoleApp_Test/UnitTest1.cs
  sources/Morvarid Arab/test/SrcWebApi_Test/GlobalUsings.cs
  sources/Morvarid Arab/test/SrcWebApi_Test/SrcWebApi_Test.csproj
  sources/Morvarid Arab/test/SrcWebApi_Test/UnitTest1.cs
  sources/README.md
Labels: ** ready to review **

#9 Feat/abolfazl kabiri
  sources/Abolfazl Kabiri/CLI tool/CLITool.MahaBuilder/CLITool.MahaBuilder.csproj
  sources/Abolfazl Kabiri/CLI tool/CLITool.MahaBuilder/GrammaticalPatterns/TemplatePattern.cs
  sources/Abolfazl Kabiri/CLI tool/CLITool.MahaBuilder/Program.cs
  sources/Abolfazl Kabiri/CLI tool/CLITool.MahaBuilder/Templates/Template.cs
  sources/Abolfazl Kabiri/CLI tool/CLITool.sln
  sources/Abolfazl Kabiri/CLI tool/readme.md
  sources/Abolfazl Kabiri/README.md
  sources/Abolfazl Kabiri/dotnet-CLI.sln
  sources/Abolfazl Kabiri/src/dotnet-CLI.ClassLibrary/Class1.cs
  sources/Abolfazl Kabiri/src/dotnet-CLI.ClassLibrary/dotnet-CLI.ClassLibrary.csproj
  sources/Abolfazl Kabiri/src/dotnet-CLI.Console/Program.cs
  sources/Abolfazl Kabiri/src/dotnet-CLI.Console/dotnet-CLI.Console.csproj
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/Program.cs
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/Properties/launchSettings.json
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/appsettings.Development.json
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/appsettings.json
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/dotnet-CLI.WebApi.csproj
  sources/Abolfazl Kabiri/src/dotnet-CLI.WebApi/dotnet-CLI.WebApi.http
  sources/Abolfazl Kabiri/test/dotnet-CLI.ClassLibrary.Tests/GlobalUsings.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.ClassLibrary.Tests/UnitTest1.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.ClassLibrary.Tests/dotnet-CLI.ClassLibrary.Tests.csproj
  sources/Abolfazl Kabiri/test/dotnet-CLI.Console.Tests/GlobalUsings.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.Console.Tests/UnitTest1.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.Console.Tests/dotnet-CLI.Console.Tests.csproj
  sources/Abolfazl Kabiri/test/dotnet-CLI.WebApi.Tests/GlobalUsings.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.WebApi.Tests/UnitTest1.cs
  sources/Abolfazl Kabiri/test/dotnet-CLI.WebApi.Tests/dotnet-CLI.WebApi.Tests.csproj
  sources/README.md
Labels: ** need some changes **

#19 Mohammad Zarei projects files
  sources/Mohammad Zarei/MySolution.sln
  sources/Mohammad Zarei/README.md
  sources/Mohammad Zarei/moha-builder/moha-builder.sln
  sources/Mohammad Zarei/moha-builder/moha-builder/MyProject1.sln
  sources/Mohammad Zarei/moha-builder/moha-builder/Program.cs
  sources/Mohammad Zarei/moha-builder/moha-builder/Properties/launchSettings.json
  sources/Mohammad Zarei/moha-builder/moha-builder/moha-builder.csproj
  sources/Mohammad Zarei/src/ClassLibProject/Class1.cs
  sources/Mohammad Zarei/src/ClassLibProject/ClassLibProject.csproj
  sources/Mohammad Zarei/src/ConsoleProject/ConsoleProject.csproj
  sources/Mohammad Zarei/src/ConsoleProject/Program.cs
  sources/Mohammad Zarei/src/WebApiProject/Program.cs
  sources/Mohammad Zarei/src/WebApiProject/Properties/launchSettings.json
  sources/Mohammad Zarei/src/WebApiProject/WebApiProject.csproj
  sources/Mohammad Zarei/src/WebApiProject/WebApiProject.http
  sources/Mohammad Zarei/src/WebApiProject/appsettings.Development.json
  sources/Mohammad Zarei/src/WebApiProject/appsettings.json
  sources/Mohammad Zarei/test/ClassLibProject.Tests/ClassLibProject.Tests.csproj
  sources/Mohammad Zarei/test/ClassLibProject.Tests/GlobalUsings.cs
  sources/Mohammad Zarei/test/ClassLibProject.Tests/UnitTest1.cs
  sources/Mohammad Zarei/test/ConsoleProject.Tests/ConsoleProject.Tests.csproj
  sources/Mohammad Zarei/test/ConsoleProject.Tests/GlobalUsings.cs
  sources/Mohammad Zarei/test/ConsoleProject.Tests/UnitTest1.cs
  sources/Mohammad Zarei/test/WebApiProject.Tests/GlobalUsings.cs
  sources/Mohammad Zarei/test/WebApiProject.Tests/UnitTest1.cs
  sources/Mohammad Zarei/test/WebApiProject.Tests/WebApiProject.Tests.csproj
  sources/README.md
Labels: ** ready to review **

#18 Feat/mahdi salahinia
  sources/Mahdi Salahinia/MyCliProjects.sln
  sources/Mahdi Salahinia/MyCliTool/MyCliTool.sln
  sources/Mahdi Salahinia/MyCliTool/README.md
  sources/Mahdi Salahinia/MyCliTool/maha-builder/ArgumentSetting.cs
  sources/Mahdi Salahinia/MyCliTool/maha-builder/Commands.cs
  sources/Mahdi Salahinia/MyCliTool/maha-builder/CommandsSetting.cs
  sources/Mahdi Salahinia/MyCliTool/maha-builder/Program.cs
  sources/Mahdi Salahinia/MyCliTool/maha-builder/maha-builder.csproj
  sources/Mahdi Salahinia/README.md
  sources/Mahdi Salahinia/src/MyClassLibProj/Class1.cs
  sources/Mahdi Salahinia/src/MyClassLibProj/MyClassLibProj.csproj
  sources/Mahdi Salahinia/src/MyConsoleProj/MyConsoleProj.csproj
  sources/Mahdi Salahinia/src/MyConsoleProj/Program.cs
  sources/Mahdi Salahinia/src/MyWebApiProj/MyWebApiProj.csproj
  sources/Mahdi Salahinia/src/MyWebApiProj/MyWebApiProj.http
  sources/Mahdi Salahinia/src/MyWebApiProj/Program.cs
  sources/Mahdi Salahinia/src/MyWebApiProj/Properties/launchSettings.json
  sources/Mahdi Salahinia/src/MyWebApiProj/appsettings.Development.json
  sources/Mahdi Salahinia/src/MyWebApiProj/appsettings.json
  sources/Mahdi Salahinia/test/ClassLib.Test/ClassLib.Test.csproj
  sources/Mahdi Salahinia/test/ClassLib.Test/GlobalUsings.cs
  sources/Mahdi Salahinia/test/ClassLib.Test/UnitTest1.cs
  sources/Mahdi Salahinia/test/ConsoleProj.Test/ConsoleProj.Test.csproj
  sources/Mahdi Salahinia/test/ConsoleProj.Test/GlobalUsings.cs
  sources/Mahdi Salahinia/test/ConsoleProj.Test/UnitTest1.cs
  sources/Mahdi Salahinia/test/WebApiProj.Test/GlobalUsings.cs
  sources/Mahdi Salahinia/test/WebApiProj.Test/UnitTest1.cs
  sources/Mahdi Salahinia/test/WebApiProj.Test/WebApiProj.Test.csproj
Labels: ** ready to review **

#16 feat:fristExercise
  sources/Mahdi_Mollaeian/README.MD
  sources/Mahdi_Mollaeian/src/MyApp.Api/MyApp.Api.csproj
  sources/Mahdi_Mollaeian/src/MyApp.Api/MyApp.Api.http
  sources/Mahdi_Mollaeian/src/MyApp.Api/Program.cs
  sources/Mahdi_Mollaeian/src/MyApp.Api/Properties/launchSettings.json
  sources/Mahdi_Mollaeian/src/MyApp.Api/appsettings.Development.json
  sources/Mahdi_Mollaeian/src/MyApp.Api/appsettings.json
  sources/Mahdi_Mollaeian/src/MyApp.Console/MyApp.Console.csproj
  sources/Mahdi_Mollaeian/src/MyApp.Console/Program.cs
  sources/Mahdi_Mollaeian/src/MyApp.Lib/Class1.cs
  sources/Mahdi_Mollaeian/src/MyApp.Lib/MyApp.Lib.csproj
  sources/Mahdi_Mollaeian/test/MyApp.Api.Test/GlobalUsings.cs
  sources/Mahdi_Mollaeian/test/MyApp.Api.Test/MyApp.Api.Test.csproj
  sources/Mahdi_Mollaeian/test/MyApp.Api.Test/UnitTest1.cs
  sources/Mahdi_Mollaeian/test/MyApp.Console.Test/GlobalUsings.cs
  sources/Mahdi_Mollaeian/test/MyApp.Console.Test/MyApp.Console.Test.csproj
  sources/Mahdi_Mollaeian/test/MyApp.Console.Test/UnitTest1.cs
  sources/Mahdi_Mollaeian/test/MyApp.Lib.Test/GlobalUsings.cs
  sources/Mahdi_Mollaeian/test/MyApp.Lib.Test/MyApp.Lib.Test.csproj
  sources/Mahdi_Mollaeian/test/MyApp.Lib.Test/UnitTest1.cs
Labels: ** ready to review **

#14 Feat/arezoo kamane
  sources/Arezoo Kamane/CLITool.sln
  sources/Arezoo Kamane/README.md
  sources/Arezoo Kamane/maha-builder/FolderName/src/ClassLibProject/Class1.cs
  sources/Arezoo Kamane/maha-builder/FolderName/src/ClassLibProject/ClassLibProject.csproj
  sources/Arezoo Kamane/maha-builder/FolderName/src/ConsoleProject/ConsoleProject.csproj
  sources/Arezoo Kamane/maha-builder/FolderName/src/ConsoleProject/Program.cs
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/Program.cs
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/Properties/launchSettings.json
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/WebApiProject.csproj
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/WebApiProject.http
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/appsettings.Development.json
  sources/Arezoo Kamane/maha-builder/FolderName/src/WebApiProject/appsettings.json
  sources/Arezoo Kamane/maha-builder/FolderName/test/ClassLibProject.Test/ClassLibProject.Test.csproj
  sources/Arezoo Kamane/maha-builder/FolderName/test/ClassLibProject.Test/GlobalUsings.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/ClassLibProject.Test/UnitTest1.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/ConsoleProject.Test/ConsoleProject.Test.csproj
  sources/Arezoo Kamane/maha-builder/FolderName/test/ConsoleProject.Test/GlobalUsings.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/ConsoleProject.Test/UnitTest1.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/WebApiProject.Test/GlobalUsings.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/WebApiProject.Test/UnitTest1.cs
  sources/Arezoo Kamane/maha-builder/FolderName/test/WebApiProject.Test/WebApiProject.Test.csproj
  sources/Arezoo Kamane/maha-builder/Program.cs
  sources/Arezoo Kamane/maha-builder/maha-builder.csproj
Labels: ** ready to review **

#22 build a .NET tool using CLI commands
  sources/Nazanin-Abbasi/README.md
  sources/Nazanin-Abbasi/src/Builder.Console/Builder.Console.csproj
  sources/Nazanin-Abbasi/src/Builder.Console/Program.cs
  sources/Nazanin-Abbasi/src/NazaninBuilder.sln
  sources/README.md
Labels: ** need some changes **

#6 Feat/niloufar mont
  sources/Niloo Mont/.gitignore
  sources/Niloo Mont/Niloo Mont.sln
  sources/Niloo Mont/README.md
  sources/Niloo Mont/mha-builder/Options.cs
  sources/Niloo Mont/mha-builder/Program.cs
  sources/Niloo Mont/mha-builder/README.md
  sources/Niloo Mont/mha-builder/mha-builder.csproj
  sources/Niloo Mont/mha-builder/mha-builder.sln
  sources/Niloo Mont/mha-builder/myCommands.bat
  sources/Niloo Mont/src/MyClassLibProject/Class1.cs
  sources/Niloo Mont/src/MyClassLibProject/MyClassLibProject.csproj
  sources/Niloo Mont/src/MyConsoleProject/MyConsoleProject.csproj
  sources/Niloo Mont/src/MyConsoleProject/Program.cs
  sources/Niloo Mont/src/MyWebApiProject/Controllers/WeatherForecastController.cs
  sources/Niloo Mont/src/MyWebApiProject/MyWebApiProject.csproj
  sources/Niloo Mont/src/MyWebApiProject/Program.cs
  sources/Niloo Mont/src/MyWebApiProject/Properties/launchSettings.json
  sources/Niloo Mont/src/MyWebApiProject/WeatherForecast.cs
  sources/Niloo Mont/src/MyWebApiProject/appsettings.Development.json
  sources/Niloo Mont/src/MyWebApiProject/appsettings.json
  sources/Niloo Mont/test/MyClassLibProject.Tests/MyClassLibProject.Tests.csproj
  sources/Niloo Mont/test/MyClassLibProject.Tests/UnitTest1.cs
  sources/Niloo Mont/test/MyClassLibProject.Tests/Usings.cs
  sources/Niloo Mont/test/MyConsoleProject.Tests/MyConsoleProject.Tests.csproj
  sources/Niloo Mont/test/MyConsoleProject.Tests/UnitTest1.cs
  sources/Niloo Mont/test/MyConsoleProject.Tests/Usings.cs
  sources/Niloo Mont/test/MyWebApiProject.Tests/MyWebApiProject.Tests.csproj
  sources/Niloo Mont/test/MyWebApiProject.Tests/UnitTest1.cs
  sources/Niloo Mont/test/MyWebApiProject.Tests/Usings.cs
  sources/README.md
Labels: ** Do Not Merge **, ** need some changes **

#24 Feat/hamidreza rahmani
  sources/Hamidreza Rahmani/README.md
  sources/Hamidreza Rahmani/maha-builder/maha-builder/Program.cs
  sources/Hamidreza Rahmani/maha-builder/maha-builder/README.md
  sources/Hamidreza Rahmani/maha-builder/maha-builder/maha-builder.csproj
  sources/Hamidreza Rahmani/src/ClassLibProject/Class1.cs
  sources/Hamidreza Rahmani/src/ClassLibProject/ClassLibProject.csproj
  sources/Hamidreza Rahmani/src/ConsoleProject/ConsoleProject.csproj
  sources/Hamidreza Rahmani/src/ConsoleProject/Program.cs
  sources/Hamidreza Rahmani/src/WebApiProject/Program.cs
  sources/Hamidreza Rahmani/src/WebApiProject/Properties/launchSettings.json
  sources/Hamidreza Rahmani/src/WebApiProject/WebApiProject.csproj
  sources/Hamidreza Rahmani/src/WebApiProject/WebApiProject.http
  sources/Hamidreza Rahmani/src/WebApiProject/appsettings.Development.json
  sources/Hamidreza Rahmani/src/WebApiProject/appsettings.json
  sources/Hamidreza Rahmani/test/ClassLibProject.Test/ClassLibProject.Test.csproj
  sources/Hamidreza Rahmani/test/ClassLibProject.Test/GlobalUsings.cs
  sources/Hamidreza Rahmani/test/ClassLibProject.Test/UnitTest1.cs
  sources/Hamidreza Rahmani/test/ConsoleProject.Test/ConsoleProject.Test.csproj
  sources/Hamidreza Rahmani/test/ConsoleProject.Test/GlobalUsings.cs
  sources/Hamidreza Rahmani/test/ConsoleProject.Test/UnitTest1.cs
  sources/Hamidreza Rahmani/test/WebApiProject.Test/GlobalUsings.cs
  sources/Hamidreza Rahmani/test/WebApiProject.Test/UnitTest1.cs
  sources/Hamidreza Rahmani/test/WebApiProject.Test/WebApiProject.Test.csproj
  sources/README.md
Labels: ** ready to review **

#3 Feature/mojtaba valizadeh
  sources/Mojtaba Valizadeh/README.md
  sources/Mojtaba Valizadeh/maha-builder/.idea/.idea.maha-builder.dir/.idea/encodings.xml
  sources/Mojtaba Valizadeh/maha-builder/.idea/.idea.maha-builder.dir/.idea/indexLayout.xml
  sources/Mojtaba Valizadeh/maha-builder/.idea/.idea.maha-builder.dir/.idea/vcs.xml
  sources/Mojtaba Valizadeh/maha-builder/Program.cs
  sources/Mojtaba Valizadeh/maha-builder/README.md
  sources/Mojtaba Valizadeh/maha-builder/maha-builder.csproj
  sources/Mojtaba Valizadeh/src/ClassLibProject/Class1.cs
  sources/Mojtaba Valizadeh/src/ClassLibProject/ClassLibProject.csproj
  sources/Mojtaba Valizadeh/src/ConsoleProject/ConsoleProject.csproj
  sources/Mojtaba Valizadeh/src/ConsoleProject/Program.cs
  sources/Mojtaba Valizadeh/src/WebApiProject/.idea/.idea.WebApiProject.dir/.idea/encodings.xml
  sources/Mojtaba Valizadeh/src/WebApiProject/.idea/.idea.WebApiProject.dir/.idea/indexLayout.xml
  sources/Mojtaba Valizadeh/src/WebApiProject/.idea/.idea.WebApiProject.dir/.idea/vcs.xml
  sources/Mojtaba Valizadeh/src/WebApiProject/.idea/config/applicationhost.config
  sources/Mojtaba Valizadeh/src/WebApiProject/Program.cs
  sources/Mojtaba Valizadeh/src/WebApiProject/Properties/launchSettings.json
  sources/Mojtaba Valizadeh/src/WebApiProject/WebApiProject.csproj
  sources/Mojtaba Valizadeh/src/WebApiProject/WebApiProject.http
  sources/Mojtaba Valizadeh/src/WebApiProject/appsettings.Development.json
  sources/Mojtaba Valizadeh/src/WebApiProject/appsettings.json
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/.idea/.idea.ClassLibProject.Test.dir/.idea/encodings.xml
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/.idea/.idea.ClassLibProject.Test.dir/.idea/indexLayout.xml
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/.idea/.idea.ClassLibProject.Test.dir/.idea/vcs.xml
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/ClassLibProject.Test.csproj
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/GlobalUsings.cs
  sources/Mojtaba Valizadeh/test/ClassLibProject.Test/UnitTest1.cs
  sources/Mojtaba Valizadeh/test/ConsoleProject.Test/ConsoleProject.Test.csproj
  sources/Mojtaba Valizadeh/test/ConsoleProject.Test/GlobalUsings.cs
  sources/Mojtaba Valizadeh/test/ConsoleProject.Test/UnitTest1.cs
  sources/Mojtaba Valizadeh/test/WebApiProject.Test/GlobalUsings.cs
  sources/Mojtaba Valizadeh/test/WebApiProject.Test/UnitTest1.cs
  sources/Mojtaba Valizadeh/test/WebApiProject.Test/WebApiProject.Test.csproj
  sources/README.md
Labels: ** need some changes **

#26 update readme in source
  sources/README.md
  sources/SepehrSherian/maha-builder/Maha_Builder/Program.cs
Labels: ** ready to review **

#25 Feat/amir fazlali
  sources/Amir Fazlali/README.md
  sources/Amir Fazlali/maha-builder/maha-builder-tool/Program.cs
  sources/Amir Fazlali/maha-builder/maha-builder-tool/entities/Methods.cs
  sources/Amir Fazlali/maha-builder/maha-builder-tool/entities/Options.cs
  sources/Amir Fazlali/maha-builder/maha-builder-tool/maha-builder-tool.csproj
  sources/Amir Fazlali/maha-builder/maha-builder-tool/maha-builder-tool.sln
  sources/Amir Fazlali/maha-builder/maha-builder.sln
  sources/Amir Fazlali/src/CLI-Project.Library/CLI-Project.Library.csproj
  sources/Amir Fazlali/src/CLI-Project.Library/Class1.cs
  sources/Amir Fazlali/src/CLI-Project/CLI-Project.csproj
  sources/Amir Fazlali/src/CLI-Project/Program.cs
  sources/Amir Fazlali/src/CLI-ProjectAPI/CLI-ProjectAPI.csproj
  sources/Amir Fazlali/src/CLI-ProjectAPI/CLI-ProjectAPI.http
  sources/Amir Fazlali/src/CLI-ProjectAPI/Program.cs
  sources/Amir Fazlali/src/CLI-ProjectAPI/Properties/launchSettings.json
  sources/Amir Fazlali/src/CLI-ProjectAPI/appsettings.Development.json
  sources/Amir Fazlali/src/CLI-ProjectAPI/appsettings.json
  sources/Amir Fazlali/test/CLI-Project.Library.Tests/CLI-Project.Library.Tests.csproj
  sources/Amir Fazlali/test/CLI-Project.Library.Tests/GlobalUsings.cs
  sources/Amir Fazlali/test/CLI-Project.Library.Tests/UnitTest1.cs
  sources/Amir Fazlali/test/CLI-Project.Tests/CLI-Project.Tests.csproj
  sources/Amir Fazlali/test/CLI-Project.Tests/GlobalUsings.cs
  sources/Amir Fazlali/test/CLI-Project.Tests/UnitTest1.cs
  sources/Amir Fazlali/test/CLI-ProjectAPI.Tests/CLI-ProjectAPI.Tests.csproj
  sources/Amir Fazlali/test/CLI-ProjectAPI.Tests/GlobalUsings.cs
  sources/Amir Fazlali/test/CLI-ProjectAPI.Tests/UnitTest1.cs
Labels: ** ready to review **

#10 Feat/javid hassani
  sources/Javid Hassani/Javid Hassani.sln
  sources/Javid Hassani/Readme.md
  sources/Javid Hassani/TestAPI/Program.cs
  sources/Javid Hassani/TestAPI/Properties/launchSettings.json
  sources/Javid Hassani/TestAPI/TestAPI.csproj
  sources/Javid Hassani/TestAPI/TestAPI.http
  sources/Javid Hassani/TestAPI/appsettings.Development.json
  sources/Javid Hassani/TestAPI/appsettings.json
  sources/Javid Hassani/TestConsole/Program.cs
  sources/Javid Hassani/TestConsole/TestConsole.csproj
  sources/Javid Hassani/TestLib/Class1.cs
  sources/Javid Hassani/TestLib/TestLib.csproj
  sources/Javid Hassani/test/ClassLib.Tests/ClassLib.Tests.csproj
  sources/Javid Hassani/test/ClassLib.Tests/GlobalUsings.cs
  sources/Javid Hassani/test/ClassLib.Tests/UnitTest1.cs
  sources/Javid Hassani/test/Console.Tests/Console.Tests.csproj
  sources/Javid Hassani/test/Console.Tests/GlobalUsings.cs
  sources/Javid Hassani/test/Console.Tests/UnitTest1.cs
  sources/Javid Hassani/test/WebApi.Tests/GlobalUsings.cs
  sources/Javid Hassani/test/WebApi.Tests/UnitTest1.cs
  sources/Javid Hassani/test/WebApi.Tests/WebApi.Tests.csproj
Labels: ** Do Not Merge **

#12 Feat/somayeh mehri
  sources/Somayeh Mehri/CLISample.sln
  sources/Somayeh Mehri/README.md
  sources/Somayeh Mehri/src/CLIClassLib/CLIClassLib.csproj
  sources/Somayeh Mehri/src/CLIClassLib/Class1.cs
  sources/Somayeh Mehri/src/CLIConsole/CLIConsole.csproj
  sources/Somayeh Mehri/src/CLIConsole/Program.cs
  sources/Somayeh Mehri/src/CLIWebApi/CLIWebApi.csproj
  sources/Somayeh Mehri/src/CLIWebApi/Controllers/WeatherForecastController.cs
  sources/Somayeh Mehri/src/CLIWebApi/Program.cs
  sources/Somayeh Mehri/src/CLIWebApi/Properties/launchSettings.json
  sources/Somayeh Mehri/src/CLIWebApi/WeatherForecast.cs
  sources/Somayeh Mehri/src/CLIWebApi/appsettings.Development.json
  sources/Somayeh Mehri/src/CLIWebApi/appsettings.json
  sources/Somayeh Mehri/test/CLIClassLib.Test/CLIClassLib.Test.csproj
  sources/Somayeh Mehri/test/CLIClassLib.Test/GlobalUsings.cs
  sources/Somayeh Mehri/test/CLIClassLib.Test/UnitTest1.cs
  sources/Somayeh Mehri/test/CLIConsole.Test/CLIConsole.Test.csproj
  sources/Somayeh Mehri/test/CLIConsole.Test/GlobalUsings.cs
  sources/Somayeh Mehri/test/CLIConsole.Test/UnitTest1.cs
  sources/Somayeh Mehri/test/CLIWebApi.Test/CLIWebApi.Test.csproj
  sources/Somayeh Mehri/test/CLIWebApi.Test/GlobalUsings.cs
  sources/Somayeh Mehri/test/CLIWebApi.Test/UnitTest1.cs
Labels: ** Do Not Merge **
